In [1]:
R.version.string

[1] "R version 4.6.1 (2026-06-24)"

In [2]:
2 + 2
example <- matrix(c(1, 2, 3, 4, 5, 6, 7, 8), nrow = 4, ncol = 2)
example

[1] 4

     [,1] [,2]
[1,] 1    5
[2,] 2    6
[3,] 3    7
[4,] 4    8

In [3]:
install.packages("stringr")
install.packages("BiocManager")
BiocManager::install("Biobase", update = FALSE, ask = FALSE)
install.packages("remotes")
remotes::install_github("rladies/praise")

Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)

Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)

'getOption("repos")' replaces Bioconductor standard repositories, see
'help("repositories", package = "BiocManager")' for details.
Replacement repositories:
    CRAN: https://cran.rstudio.com

Bioconductor version 3.23 (BiocManager 1.30.27), R 4.6.1 (2026-06-24)

Installing package(s) 'BiocVersion', 'Biobase'

also installing the dependency ‘BiocGenerics’


Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)

Downloading GitHub repo rladies/praise@HEAD

── R CMD build ─────────────────────────────────────────────────────────────────
* checking for file ‘/tmp/RtmpV3JaQj/remotes3fe4f0e1224/rladies-praise-094469a/DESCRIPTION’ ... OK
* preparing ‘praise’:
* checking DESCRIPTION meta-information ... OK
* checking for LF line-endings in source and make files and shell scripts
* checking for empty or unneeded directories
Omitted ‘LazyData’ from DESCRIPTION
* building ‘praise_1.0.0.tar.gz’

Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)

In [4]:
library(stringr)
library(Biobase)
library(praise)

str_to_upper("hello")
praise()

Loading required package: BiocGenerics

Loading required package: generics


Attaching package: ‘generics’


The following objects are masked from ‘package:base’:

    as.difftime, as.factor, as.ordered, intersect, is.element, setdiff,
    setequal, union



Attaching package: ‘BiocGenerics’


The following objects are masked from ‘package:stats’:

    IQR, mad, sd, var, xtabs


The following objects are masked from ‘package:base’:

    anyDuplicated, aperm, append, as.data.frame, basename, cbind,
    colnames, dirname, do.call, duplicated, eval, evalq, Filter, Find,
    get, grep, grepl, is.unsorted, lapply, Map, mapply, match, mget,
    order, paste, pmax, pmax.int, pmin, pmin.int, Position, rank,
    rbind, Reduce, rownames, sapply, saveRDS, table, tapply, unique,
    unsplit, which.max, which.min


Welcome to Bioconductor

    Vignettes contain introductory material; view with
    'browseVignettes()'. To cite Bioconductor, see
    'citation("Biobase")', and for packages 'citation("pkgname")'.

[1] "HELLO"

[1] "You are wise!"

docs

In [8]:
help(package = "stringr")

In [9]:
?str_detect

In [10]:
?praice

vignettes

In [11]:
vignette(package = "stringr")$results[, c("Item", "Title")]

     Item                Title
[1,] from-base           From base R (source, html)
[2,] stringr             Introduction to stringr (source, html)
[3,] locale-sensitive    Locale sensitive functions (source, html)
[4,] regular-expressions Regular expressions (source, html)

In [12]:
vignette(package = "Biobase")$results[, c("Item", "Title")]

     Item
[1,] ExpressionSetIntroduction
[2,] esApply
[3,] BiobaseDevelopment
     Title
[1,] An introduction to Biobase and ExpressionSets (source, pdf)
[2,] esApply Introduction (source, html)
[3,] Notes for eSet developers (source, html)

packages

In [17]:
pkgs <- installed.packages()[, c("Package", "Version")]
head(pkgs, 20)

             Package      Version
Biobase      Biobase      2.72.0
BiocGenerics BiocGenerics 0.58.1
BiocManager  BiocManager  1.30.27
BiocVersion  BiocVersion  3.23.1
IRdisplay    IRdisplay    1.1
IRkernel     IRkernel     1.3.2
pbdZMQ       pbdZMQ       0.3-14
praise       praise       1.0.0
remotes      remotes      2.5.0
repr         repr         1.1.7
stringr      stringr      1.6.0
askpass      askpass      1.2.1
backports    backports    1.5.1
base64enc    base64enc    0.1-6
bit          bit          4.6.0
bit64        bit64        4.8.6
blob         blob         1.3.0
boot         boot         1.3-32
brew         brew         1.0-10
brio         brio         1.1.5

In [18]:
old.packages()

         Package  LibPath                 Installed
curl     curl     /usr/lib/R/site-library 8.0.0
foreign  foreign  /usr/lib/R/site-library 0.8-91
gert     gert     /usr/lib/R/site-library 2.4.1
readxl   readxl   /usr/lib/R/site-library 1.5.0.1
roxygen2 roxygen2 /usr/lib/R/site-library 8.1.0
xfun     xfun     /usr/lib/R/site-library 0.61
xtable   xtable   /usr/lib/R/site-library 1.8-4
         Built                                                       ReposVer
curl     R 4.6.1; x86_64-pc-linux-gnu; 2026-08-25 20:19:02 UTC; unix 8.1.0
foreign  R 4.6.1; x86_64-pc-linux-gnu; 2026-07-15 21:11:31 UTC; unix 0.8-92
gert     R 4.6.1; x86_64-pc-linux-gnu; 2026-08-19 16:47:24 UTC; unix 2.5.0
readxl   R 4.6.1; x86_64-pc-linux-gnu; 2026-09-16 11:49:37 UTC; unix 1.6.0
roxygen2 R 4.6.1; x86_64-pc-linux-gnu; 2026-08-05 01:23:43 UTC; unix 8.1.1
xfun     R 4.6.1; x86_64-pc-linux-gnu; 2026-09-17 01:21:16 UTC; unix 0.62
xtable   R 4.0.1; ; 'Fri, 15 May 2020 22:52:46 +0200'; unix          1.8-8
         Repository
curl     https://cran.rstudio.com/src/contrib
foreign  https://cran.rstudio.com/src/contrib
gert     https://cran.rstudio.com/src/contrib
readxl   https://cran.rstudio.com/src/contrib
roxygen2 https://cran.rstudio.com/src/contrib
xfun     https://cran.rstudio.com/src/contrib
xtable   https://cran.rstudio.com/src/contrib

В colab создавать проект R нельзя :(